name: CubeLib
description: A 3d rendering library based on interop with babylon.js.
version: 0.0.1
homepage: https://github.com/FarragoFiction/CubeLib
author: paradoxLands

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git
  LoaderLib:
    git: git://github.com/FarragoFiction/LoaderLib.git

dev_dependencies:
  test: ^0.12.0
