name: CubeLib
description: A 3d rendering library based on interop with babylon.js.
version: 0.0.1
homepage: https://github.com/FarragoFiction/CubeLib
author: paradoxLands

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
